"""Add action_id to conversation_turns

Revision ID: 91ccb89931b8
Revises: a1b2c3d4e5f6
Create Date: 2026-01-18 18:25:05.772721

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "91ccb89931b8"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversation_turns", sa.Column("action_id", sa.String(length=36), nullable=True))
    op.create_index(
        op.f("ix_conversation_turns_action_id"), "conversation_turns", ["action_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_conversation_turns_action_id"), table_name="conversation_turns")
    op.drop_column("conversation_turns", "action_id")
    # ### end Alembic commands ###
